### ISSUE TITLE
Error when running demo code provided

### ISSUE THREAD

**Issue by abhinavxrai** [mape/node-scraper#3]
Scraper was working fine, suddenly tonight it started gving me errors. I rebuilt my node.js server and didnt resolve the issue. If I run the following demo code, I get the same error. Any ideas?

Demo Code:
var scraper = require('scraper');
scraper('http://search.twitter.com/search?q=javascript', function(err, jQuery) {
    if (err) {throw err}

```
jQuery('.msg').each(function() {
    console.log(jQuery(this).text().trim()+'\n');
});
```

});

Error:
TypeError: Cannot read property '1' of null
    at [object Context]:6348:45
    at [object Context]:8316:2
    at Object.javascript (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/languages/javascript.js:17:14)
    at Object._eval (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:1195:46)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:43:20
    at Object.check (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:235:34)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:251:12
    at IncomingMessage.<anonymous> (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:85:11)
    at IncomingMessage.emit (events.js:59:20)
    at HTTPParser.onMessageComplete (http.js:111:23)
TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at /usr/local/lib/node/.npm/scraper/0.0.7/package/lib/scraper.js:57:7
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom.js:151:30
    at Object.<anonymous> (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/events.js:274:17)
    at Object.dispatchEvent (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:415:55)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:56:15
    at Object.check (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:235:34)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:251:12
    at IncomingMessage.<anonymous> (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:85:11)
    at IncomingMessage.emit (events.js:59:20)

**Comment by abhinavxrai** [comment]
Anyone have any ideas?
I rebuilt my instance and re-installed node and scraper. Same issue

**Comment by fat** [comment]
I'm having the same issue :(

**Comment by abhinavxrai** [comment]
It seems this issue started around the same time as 'request' was moved to a different tree. Are there any hard-coded  links in scraper?

**Comment by mape** [comment]
The issue seems to be with jsdom. An issue has already been raised here https://github.com/tmpvar/jsdom/issues#issue/149

**Comment by mape** [comment]
Seems jsdom defaults to:

```
jQueryTag.src = path || 'http://code.jquery.com/jquery-latest.js';
```

and that doesn't work all as it is now. I therefore reverted to a local 1.3.2 version of jQuery. 

It also seems to break on script tags in the supplied source so to prevent that I temporarily do:

```
body = body.replace(/<(\/?)script/g, '<$1nobreakage');
```

**Comment by mape** [comment]
So if it was not working for you before, update (new version on npm) and it should work.

**Comment by abhinavxrai** [comment]
Interesting, thanks for the suggestion, but even with the latest version (0.08) it fails.

Also, it seems  jQueryTag.src = path || 'http://code.jquery.com/jquery-latest.js'; should be valid

**Comment by abhinavxrai** [comment]
I raised the issue with jsdom

**Comment by abhinavxrai** [comment]
In your code I noticed:
'/../deps/jquery-1.3.2.js'

so I added a local copy of jquery 1.3.2 and still same error.

**Comment by fat** [comment]
I got my own jquery scraping thing working last night by doing something similar to this:

https://github.com/chriso/node.io/blob/master/lib/node.io/dom.js#L49

not sure if that helps...

cheers!

**Comment by mape** [comment]
jquery-1.3.2.js is already added in the project so you shouldn't have to add it on your own.

I'm not having any issues so a stack trace would be helpful.

**Comment by abhinavxrai** [comment]
TypeError: Cannot read property 'prototype' of undefined
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/browser/index.js:84:16
    at String.<anonymous> ([object Context]:2500:12)
    at Function.each ([object Context]:692:29)
    at Object.add ([object Context]:2478:10)
    at [object Context]:2907:17
    at Function.each ([object Context]:692:29)
    at Object.each ([object Context]:155:17)
    at Object.one ([object Context]:2906:15)
    at Object.bind ([object Context]:2896:34)
    at [object Context]:3106:18
    at [object Context]:4376:2
    at Object.javascript (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/languages/javascript.js:17:14)
    at Object._eval (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:1195:46)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:43:20
    at Object.check (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:235:34)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:251:12
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)
    at afterRead (fs.js:843:12)
TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at /usr/local/lib/node/.npm/scraper/0.0.8/package/lib/scraper.js:58:7
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom.js:151:30
    at Object.<anonymous> (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/events.js:274:17)
    at Object.dispatchEvent (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:415:55)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:56:15
    at Object.check (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:235:34)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:251:12
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)

**Comment by mape** [comment]
And what example do you run to get that result? Or what code.

**Comment by abhinavxrai** [comment]
I'm using your demo code:

var scraper = require('scraper');
scraper('http://search.twitter.com/search?q=javascript', function(err, jQuery) {
    if (err) {throw err}

```
jQuery('.msg').each(function() {
    console.log(jQuery(this).text().trim()+'\n');
});
```

});

**Comment by abhinavxrai** [comment]
I just rebuilt my server and installed node and scraper (0.0.8) from scratch

**Comment by mape** [comment]
Hmm I can not reproduce that error.

**Comment by abhinavxrai** [comment]
Interesting...
I'm using request@1.9.0
jsdom@0.2.0
scraper@0.0.8

I'll try to use the "advanced" demo code and see if I can replicate it.

**Comment by abhinavxrai** [comment]
I'm running 
npm@0.3.9
node@v0.5.0-pre

What versions are you running?

**Comment by mape** [comment]
node v0.4.1
npm 0.3.9

**Comment by abhinavxrai** [comment]
I downgraded to 
node@0.4.1 
still the same error. 

TypeError: Cannot read property 'prototype' of undefined

My server is running on rackspace cloud, but I've successfully used scraper before.

**Comment by DenisMir** [comment]
I got the error as well. Here is my setup: 

node v0.4.1
npm 0.3.9

I am using the latest scraper version installed via npm. I would appreciate some help.
